IMAGE:
  RESIZE_RATIO: 0.4
  CROP_RATIO: 1
  PYRAMID_LAYER: 3
MATCH_PARAMETER:
  SIFT_KEYPOINTS_NUM: 2000
  MIN_MATCH_NUM: 10
  DISTANCE_MODE: BruteForce
  DISTANCE_THRESHOLD: 0.7
  DETECTOR: sift #sift surf

TRANS_MODEL:
  GEO_TRANS_MODEL: four_param
  STITCH_TRANS_MODEL: homo # homo ; affine

STITCH_PARAMETER:
  MIN_OVERLAP: 0.1
  MAX_OVERLAP: 0.8
  RELATIVE_FRAME_OVERLAP_THRESHOLD: 0.2
  SEARCH_FRAME_NUM: 3
  MODEL_BASE_FRAME_NUM: 9

OTHER:
  IMAGE_PATH: todo
  SAVE_PATH: todo


DATALOADER:
  NUM_WORKERS: 0
DATASET:
  AUGMENTATION:
    FLIPS: true
  MODALITIES:
    3D_LABEL: true
    3D_OCCLUDED: true
    3D_OCCUPANCY: true